name: crowdleague
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  built_value:
  built_collection:
  redux:
  flutter_redux:
  redux_remote_devtools:
  
  firebase_auth:
  google_sign_in:
  apple_sign_in:
  flutter_auth_buttons:
  google_maps_flutter:
  cloud_firestore:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
  build_runner:
  built_value_generator:
  pedantic:
  test:
  mockito:

flutter:
  uses-material-design: true
  fonts:
    - family: maticons
      fonts:
        - asset: assets/fonts/maticon.ttf

# "launcher_icon" 

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app-icon-large-white.png"