name: Android

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build, test and distribute
    runs-on: ubuntu-latest
    steps:

    # several actions use checkout 
    - name: Install checkout
      uses: actions/checkout@v1
    
    ##############################################
    # flutter-action
    ##############################################
    # the flutter-action action seems to need java
    - name: Install Java, for building Flutter tool
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    # use flutter-action configured with flutter channel
    - name: Install Flutter tool
      uses: subosito/flutter-action@v1
      with:
        channel: 'dev' # or: 'stable' or 'beta'

    ##############################################
    # setup-gcloud
    ##############################################
    # the setup-gcloud action seems to need python
    - name: Install python, for building gcloud
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    # use setup-gcloud configured with auth credentials 
    - name: Install gcloud and use gsutil to download credentials
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GCS_EMAIL }}
        service_account_key: ${{ secrets.GCS_KEY }}

    - run: gsutil cp gs://crowdleague-ci-credentials/EnspyrKeystore ./android/EnspyrKeystore
    - run: gsutil cp gs://crowdleague-ci-credentials/key.properties ./android/key.properties
    - run: gsutil cp gs://crowdleague-ci-credentials/api-6095168526928626772-298708-d02eb03add02.json ./android/fastlane/api-6095168526928626772-298708-d02eb03add02.json

    - run: flutter pub get
    - run: flutter test
    - run: flutter build appbundle --build-number=$GITHUB_RUN_NUMBER

    ##############################################
    # runs fastlane to deploy to play store 
    ##############################################
    # - uses: maierj/fastlane-action@v1.4.0
    #   with:
    #     lane: 'deploy_to_play_store'
    #     subdirectory: 'android'

    ##############################################
    # Firebase App Distribution
    ##############################################
    - name: Deploy to Firebase App Distribution
      uses: w9jds/firebase-action@master
      with:
        args: appdistribution:distribute build/app/outputs/bundle/release/app-release.aab --app 1:1085919333383:android:d90b1f1799381a8c132ea2
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}